### ISSUE TITLE
Bryant, P. (2010). Optimized synchronization of chaotic and hyperchaotic system

### ISSUE THREAD

**Issue by danieltomasz** [TomDonoghue/AperiodicHistory#10]
Bryant, P. (2010). Optimized synchronization of chaotic and hyperchaotic systems. Physical Review. E, Statistical, Nonlinear, and Soft Matter Physics, 82, 015201. https://doi.org/10.1103/PhysRevE.82.015201

**Comment by TomDonoghue** [comment]
This seems to be within the domain of chaotic / dynamical systems, looking at Lyapunov exponents - and there isn't any neural data
