### ISSUE TITLE
Volf, N. V., & Gluhih, A. A. (2011). Background cerebral electrical activity in healthy mental aging.

### ISSUE THREAD

**Issue by danieltomasz** [TomDonoghue/AperiodicHistory#6]
Volf, N. V., & Gluhih, A. A. (2011). Background cerebral electrical activity in healthy mental aging. Human Physiology, 37(5), 559–567. https://doi.org/10.1134/S0362119711040207

**Comment by TomDonoghue** [comment]
This is band-by-band analysis - no aperiodic measure or discussion
