### ISSUE TITLE
Miyazaki, S., & Hata, H. (1998). Universal scaling law of the power spectrum in the on-off intermittency. 

### ISSUE THREAD

**Issue by danieltomasz** [TomDonoghue/AperiodicHistory#7]
Miyazaki, S., & Hata, H. (1998). Universal scaling law of the power spectrum in the on-off intermittency. Physical Review E, 58(6), 7172–7175. https://doi.org/10.1103/PhysRevE.58.7172

**Comment by TomDonoghue** [comment]
This isn't about any neuro data
