### ISSUE TITLE
Korn, H., & Faure, P. (2003). Is there chaos in the brain? II. Experimental evidence and related models. 

### ISSUE THREAD

**Issue by danieltomasz** [TomDonoghue/AperiodicHistory#8]
Korn, H., & Faure, P. (2003). Is there chaos in the brain? II. Experimental evidence and related models. Comptes Rendus. Biologies, 326(9), 787–840. https://doi.org/10.1016/j.crvi.2003.09.011

**Comment by TomDonoghue** [comment]
This looks like a pretty good overview of chaos - but covering all discussions of chaos is out of scope, there nothing specific about spectral measures in EEG
