### ISSUE TITLE
Allegrini, P., Menicucci, D., Bedini, R., Fronzoni, L., Gemignani, A., Grigolini, P., West, B. J., & Paradisi, P. (2009). Spontaneous brain activity as a source of ideal 1/f noise

### ISSUE THREAD

**Issue by danieltomasz** [TomDonoghue/AperiodicHistory#9]
Allegrini, P., Menicucci, D., Bedini, R., Fronzoni, L., Gemignani, A., Grigolini, P., West, B. J., & Paradisi, P. (2009). Spontaneous brain activity as a source of ideal $1/f$ noise. Physical Review E, 80(6), 061914. https://doi.org/10.1103/PhysRevE.80.061914

**Comment by TomDonoghue** [comment]
This is in the DFA world - it's an interesting paper, but this project doesn't / can't try to review all DFA related work
